### ISSUE TITLE
Mitsubishi EF35 connection problems

### ISSUE THREAD

**Issue by JohanKSE** [XattSPT/com.melcloud#15]
Hi,

I'm trying to use the app with my EF35 but it doesn't matter what I do, it won't work. I log in to the app with the same mail/pw as I use for the MelCloud and it start searching for devices. After 30000ms I get a time out and that's it.

I'm adding it as an AC device (also tried Heatpump), I have uninstalled and installed the app again. I've tested with the pump running/not running, being logged in/not logged in to the MelCloud app, removed the AC from MelCloud and then added it again etc.

Any idea what I can test next?

Rgds/Johan

**Comment by XattSPT** [comment]
hi @JohanKSE,

I list things you can try:

1) if you have devices structured in buildings, floors or zones in Melcloud app, change this configuration and try to add again on homey. I could not test every configuration, so it's possible your configuration fails. easy one is no buildings, no floors and no zones. 

2) try to change your melcoud password and then try again on Homey App. 

3) in Melcloud App invite yourself as a guest (and give maximum powers) in other email account, and try with that account. 

4) If nothing works, you can invite me (I'll provide you my email) and I can try to add your devices in my homey and try to follow step by step what is going wrong. 

5) If works in my homey and account, last desesperate option is to put an easy pwd to your melcloud account and share it with me and I'll do same as 4 but with your account. I'll test it and after that you can change again your pswd. Weekends are best time to do this because I have more time to test.

**Comment by JohanKSE** [comment]
Thanks, I will try this out later to day and let you know how it goes.

Thanks for excellent help!

Mvh/Johan

Johan Karlson
Länsmansvägen 9, 446 32 Älvängen, Sweden.
Tel: 0707-86 59 10.
E-post: johan@karlson.in


Den lör 30 maj 2020 09:51Gerard Ricart <notifications@github.com> skrev:

**Comment by JohanKSE** [comment]
Hi, sorry to have to bother you again but I'm still stuck. What I've tested
today:

Added presets (figured maybe you iterate through them after you found a
device)
Added missing info for the outside unit
Created floor and zone and shifted it between (default it was just in the
building, se pic attached.).
Switched language to English (originally it was Swedish so thought our åäö
could have messed it up)
Simplified my own password
Created a guest account, simple password.

Feel a bit embarrassed but it you have the time I would greatly appreciate
if you could you test it. If you want we can go straight to me changing to
a simple password and give you full access for a while (seems it would be
the simplest way for you)?

Again thanks and have a great Saturday evening,

[image: image.png]
Created a floor and added the device to it
created a zone and added the device to it

Created a guestaccound and used a simple password
*Johan Karlson*
Länsmansvägen 9, 446 32 Älvängen, Sweden.
Tel: 0303-74 91 94. Mobil: 0707-86 59 10.
E-post: johan@karlson. <johan@karlson.in>in


Den lör 30 maj 2020 kl 09:51 skrev Gerard Ricart <notifications@github.com>:

**Comment by XattSPT** [comment]
Send me an invitation on Melcloud or your usr/pswd at gerard.ricart@gmail.com
