### ISSUE TITLE
Show chosen heat mode

### ISSUE THREAD

**Issue by Katatonz** [XattSPT/com.melcloud#31]
I see that the app shows the same as melcloud when it comes to heat mode. I have a ecodan air /water unit and use heat curve in relation to outdoor temperature. The app and melcloud show room temperature even when that mode is not chosen. Could you rather show target temperature and actual temperature instead. Gives a better indication if the machine struggles to reach target. Would also be nice to see temperatures on different subsystems, like thw6 and 7.

**Comment by OlivierZal** [comment]
Hi @Katatonz, I'm the new developer of the app.

I'm not sure I get your point since "room temperature" corresponds to the "actual temperature" in MELCloud.

Anyway, the display does not depend on the code but on Homey's standard capabilities for thermostat, so I don't think it's possible to change it.

Don't hesitate to tell me if I didn't understand your proposal!

For your information I've just published a new version of the app for testing: https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

Regards

**Comment by OlivierZal** [comment]
I close this issue because of standard capabilities limitations and since I will propose soon a new version of the app which should address your request.

**Comment by Katatonz** [comment]
Hi OlivierZal,
Sorry for delayed response. Let me clarify, the "Room temperature" for an Ecodan/Water unit corresponds to the temperature in the indoor unit. This box is often placed in a technical room and could have a completely different room temperature than what is actual for the entire house or wanted reference temperature. Off course if accessories such as PAR-WT50R-E (wireless controller) or PAC-SE41T-E (external cabled room temperature sensor) is present the system can be controlled by room temperature. If not, the other way to control the unit is by setting a heating curve, where the actual leaving water temperature corresponds to pre configured curve based on outdoor temperature. So f.ex in my system with floor heating I have 38˚C water temperature at -10˚C outdoor temperature and 28˚C water temperature at +15˚C outdoor temperature. By seeing target water temp in app one can see if the system is delivering at correct temperature, and debug if other systems are giving warnings.
