### ISSUE TITLE
Eco Hot Water

### ISSUE THREAD

**Issue by FridhF** [XattSPT/com.melcloud#48]
Eco hot water does not work on the ecodan.

**Comment by OlivierZal** [comment]
Hi @FridhF, after investigation, maybe it's more a limitation of the MELCloud API: the former developer added this value in the settings and but the value was not sent to MELCloud.

You can install this testing https://homey.app/a/com.mecloud/test/, which solves some couple of bugs.
Now this value is displayed in the dashboard rather than in the settings and is "read-only", so that you can see the value, but – at least for the moment – I didn't find any serious documentation telling how to send this value (if even it's possible).

If I get some ideas I will make some tests, so I keep this issue open for the moment.

**Comment by OlivierZal** [comment]
Exactly @XattSPT. 

I found nothing neither on HomeAssistant or on pymelcloud. 

I will probably write a script and increment EffectiveFlags until it changes EcoHotWater. 

@FridhF that’s why I keep your issue open, keep faith 😉

**Comment by OlivierZal** [comment]
@FridhF, I have an idea: do you see any button on MELCloud website enabling you to activate / deactivate Eco Hot Water? If so and if you agree to grant a temporary full guest access (available un the settings) to your MELCloud, I can add it.

**Comment by OlivierZal** [comment]
@FridhF, I think I've kind of proved that MELCloud API does not support EcoHotWater modification: I tried the highest `EffectiveFlags` supported by the API (`9223372036854775807` – `9223372036854775808` and above cause a code 500) and EcoHotWater stil doesn't change.
