### ISSUE TITLE
Bug: When Operation Mode Change

### ISSUE THREAD

**Issue by kajo23** [XattSPT/com.melcloud#8]
Using the Flow:
When > Operation Mode Changed to: HDW-Heating works opposite. It trigger when DHW Heating is finished instead of when starts.

Example. My DHW start to Heat at 08.49h. At this time trigger have to be ON. At 09.49h DHW Heating goes OFF then trigger goes ON and "Message" appear. I use message to debug.

BTW correct is DHW not HDW on the label.
Thank you for this app.

**Comment by XattSPT** [comment]
@kajo23 

Tried to solve the problem on trigger mode... (not sure if it will work correctly) If not, it will be helpful for me if you can test if only trigger is the problem or any reports on conditions or actions with Operation Mode are working correctly. 

You can Test it on: https://homey.app/a/com.mecloud/test/

Also Added this Flowcards:
 - Triggers: Hot Water Flow Change, Cold Water Flow Change
 - Conditions: Hot Water is bigger than, Cold Water is lower than
 - Actions: Set Heat Water, Set Cool Water  

With this and a couple of varibles on Homey App you can solve the problem you told me a week ago ;-)

Please, test it and tell me if works correctly previous to public release.

**Comment by kajo23** [comment]
After installing app from link I see following bug.
Bug: target temperature set to 30C. I set it to correct one 24 but after few seconds it is back to 30C

**Comment by XattSPT** [comment]
ouch... 

I know it's anoying (it will break existing Flows) but... can you try to delete Device and Readd?

One more question, do you have one Zone or two?

**Comment by kajo23** [comment]
One zone

**Comment by XattSPT** [comment]
@kajo23 if do not work readding device... install public version of app. I'll will investigate, this is really not expected (not touched anything on target temperature) :(

**Comment by kajo23** [comment]
After ReAdd device now it looks ok. I am testing now

**Comment by kajo23** [comment]
When I use flow to Set Heating Water Flow > parameter set correct in settings screen but do not update on the machine.

When i change this parameter from settings screen it updates immediately to machine

**Comment by XattSPT** [comment]
@kajo23 

Action: Set Heating Water Flow
When I use flow to Set Heating Water Flow > parameter set correct in settings screen but do not update on the machine.
When i change this parameter from settings screen it updates immediately to machine
**SOLVED will publish new test this afternoon**

Trigger: Inside Temp
When I use as trigger: Inside Temp test flow does not pass 
**Need more info. I don't know what is inside Temp as Trigger**

When I set trigger to start flow it passed

All Triggers: DIDN'T WORK AT ALL. Test flow can not pass.  **Need more info, most of Triggers are standard from app (ex tempertatures) and should work**

Trigger: Operation Mode has changed to Heating trigger when Off instead when On
**Done some tests ans seems to work. Think is solved(not sure)**

In Trigger string is DHW-Heating
In condition when using logic as Mode I see it HDW-Heating **SOLVED**

PS: can you also add/read compressor from MELCloud. From there I catch that my pump do not work as it should works. Explanation from Mitsubishi is that my pump is bigger then I needed. But local installer do not want to change because they do not do this as service
**There is almost all information available on Melcoud. Only is pending by my side to put energy consumption, but no info regarding Compressor seems to be on data.**

**Comment by XattSPT** [comment]
published new test.

**Comment by kajo23** [comment]
How to test? Again from link above? And ReAdd device i guess

**Comment by XattSPT** [comment]
Only install from same link.

I think I’ve solved the problem on data, so no need to readd device.
Install and test only!

El dg, 12 gen 2020 a les 11:07 kajo23 <notifications@github.com> va
escriure:

**Comment by kajo23** [comment]
ACTION: Set Heating Water Flow - WORKS

CONDITION: Operation mode is equal: Heating. And it is Heating at the moment FALSE

I continue to test and update this post

**Comment by XattSPT** [comment]
@kajo23 published new test. Hope all works now. (operationMode Flowcard (99% sure now it's correct)) and all other bugfixes. 

Also your suggestion that I think logic.

I'll sent it to certification. No more time this week for hobbies :)

Write me if you discover any bug or suggestion.

**Comment by kajo23** [comment]
**ACTION:** Set Heating Water Flow - WORKS
**CONDITION:** OPERATION MODE IS EQUAL - WORKS

**TRIGGER:** Operation Mode Changed to **Heating** - Still works opposite when changed from Heating to DHW-Heating

**SUGGESTION 1:**
With TRIGGER: **Operation Mode Changed** and CONDITION: OPERATION MODE IS EQUAL can be verified desired MODE and this is enough to make a working flows.

Now my pump works like a charm. All the time at min power without unreasonable stops till room temp is achieved.

**SUGGESTION 2:**
Set Cool Water Zone is limited to 10C. Heat Pump allows this parameter to be set to 7C so it is good to restrict it to same number 

I want to share the flow to guys who want to use it:
**Flow 1: **
Operation Mode is equal **OFF** for long period
THEN: **Set Heat Water Flow** to min. desired temp. from where to start the heating process.
**Notes:** This flow is not full because depends on the idea of the user

**Flow 2:**
**WHEN: **
    - **Every 5min** 
**AND: **
   - Operation Mode is equal **HEATING**
   - **LOGIC: **Hot Water Flow** is more then or equal to {{**Heat Water Flow Set+1}} is true 
**THEN:**
   - LOGIC: Calculate **Variable** as {{**Variable**+1}}
   - **Set Heat Water Flow** - **Variable**

**Comment by XattSPT** [comment]
@kajo23 all three suggestion applied on a new test.

If you can test and works fine, I'll will publish to public release.

Thanks for your help!

**Comment by kajo23** [comment]
Hi.  Long time no replay from my side because I don't have time for tests. 
I am still with Test App V2.0.5. I see that official app is same version. I am afraid to install latest oficial App from Homey. 
I used plenty of rules to heat my house and i am Happy at the moment 

BUG: Advanced Settings: Eco Hot Water (DHW) - "Yes to No" and "No to Yes' after Confirmation do NOT works. Return back to previous state.

TRIGGER: Operation Mode Changed
ACTION: Operation Mode returns only those 3 states: Off, DHW-Heating, Heating
SUGGESTION:  add DEFROST, maybe also rest of the operation modes. 

I want to Donate you for the job you did. But I do NOT see Donate link on the Homey page.
Regards
